# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Dldb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLDBViewer
  pod 'DLDB' , '0.9.7'

end
workspace 'Dldb'
